### ISSUE TITLE
TASK: Create sample questions/answers based on user input

### ISSUE THREAD

**Issue by ReyMPerez** [Allen-ISD-Computer-Science/REPO_InteractiveChatbotScheduling_2024#16]
Supports Story #17 
- [x] Create questions that the chatbot would ask the user at the beginning to determine what they need help with.

**Comment by JacksonA378** [comment]
https://docs.google.com/document/d/1LM9QUnODRFLB9ma3OJZ4wIsG29LDgv45j9nR2CMMzU0/edit?usp=sharing

**Comment by ReyMPerez** [comment]
Task for Sprint 8:

- [x] Create sample responses that we should anticipate from the user, so that we can train the chatbot accordingly.

**Comment by JacksonA378** [comment]
I worked on the questions/responses for the AI chatbot 

https://docs.google.com/document/d/1LM9QUnODRFLB9ma3OJZ4wIsG29LDgv45j9nR2CMMzU0/edit?usp=sharing
