### ISSUE TITLE
TASK: Add Files to Handle Graphical User Interface of Chatbot

### ISSUE THREAD

**Issue by ReyMPerez** [Allen-ISD-Computer-Science/REPO_InteractiveChatbotScheduling_2024#25]
Supports Story #13

**Comment by ReyMPerez** [comment]
@ReyMPerez and @JacksonA378 worked together to add files to the repository to handle the graphical user interface and chat function of the product, but the code was not at the appropriate level to commit yet. However, we will continue to work on the code and improve the interface.

**Comment by JacksonA378** [comment]
@JacksonA378 and @ReyMPerez worked on adding files to the repository to handle the GUI and chat function of our product, but the code wasn't ready to be committed yet.
