### ISSUE TITLE
TASK: Create basic structure for homework/activity planner based on user input

### ISSUE THREAD

**Issue by ReyMPerez** [Allen-ISD-Computer-Science/REPO_InteractiveChatbotScheduling_2024#6]
Supports Story #1

**Comment by ReyMPerez** [comment]
Tasks for Sprint 8:

- [ ]  Train the chatbot with questions with related to a student organizing their assignments and extracurricular activities
- [ ]  ~~Create variables that pertain to name, startTime, endTime, location and check if they are being stored correctly~~

**Comment by ReyMPerez** [comment]
I am unable to access the necessary python tools, so I was unable to commit. However, I collaborated with and co-authored the commit with @saip9

**Comment by saip9** [comment]
Pending tasks from Sprint 8 for Sprint 9:

- [ ]  Create variables that pertain to name, startTime, endTime, location and check if they are being stored correctly

New Tasks for Sprint 9:

- [ ]

**Comment by saip9** [comment]
Pending tasks from Sprint 8 for Sprint 9:

- [ ]  Train the chatbot with questions with related to a student organizing their assignments and extracurricular activities (Partially completed in Sprint 8)
